"""generate db

Revision ID: 6947af7351c2
Revises: 
Create Date: 2021-02-11 21:21:54.672483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6947af7351c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('img_data', sa.Text(length=16777216), nullable=True),
    sa.Column('img_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='unq_image_id')
    )
    op.create_index('idx_image_id', 'image', ['id'], unique=False)
    op.create_table('logentry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('repeats', sa.Numeric(), nullable=False),
    sa.Column('alert_type', sa.String(length=15), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('operation', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='unq_logentry_id')
    )
    op.create_index('idx_logentry_id', 'logentry', ['id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Text(length=16777216), nullable=True),
    sa.Column('attachment_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['logentry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='unq_message_id')
    )
    op.create_index('idx_message_id', 'message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_message_id', table_name='message')
    op.drop_table('message')
    op.drop_index('idx_logentry_id', table_name='logentry')
    op.drop_table('logentry')
    op.drop_index('idx_image_id', table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
