{
 "title": "PROD LOGIN CHECK LOGS",
 "time": { "from": "2021-02-11T22:16:55.016Z", "to": "2021-02-12T10:16:55.018Z" },
 "panels": [
  {
   "title": "LOGIN STATUS",
   "type": "timeseries",
   "description": "0 - Good\n1 - ERROR",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  create_at AS \"time\",\n  value\nFROM logentry\nWHERE\n  $__timeFilter(create_at)\nORDER BY create_at"
    }
   ]
  },
  {
   "title": "Failures/Retries",
   "type": "table",
   "gridPos": { "h": 20, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n  message.create_at as TimeStamp,\n  value, \n  operation,\n  message as Log, \n  img_url\nFROM logentry\n  INNER JOIN message ON message.session_id = logentry.id \n  INNER JOIN image ON message.attachment_id = image.id  \nWHERE \n  $__timeFilter(message.create_at) \nORDER BY \n  message.create_at desc"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "table",
   "gridPos": { "h": 20, "w": 17, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT \n  message.create_at as TimeStamp,\n  value, \n  operation,\n  message as Log\nFROM logentry\n  INNER JOIN message ON message.session_id = logentry.id \nWHERE \n  $__timeFilter(message.create_at) \nORDER BY \n  message.create_at desc"
    }
   ]
  }
 ]
}