{
 "title": "test infra",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "esxhost",
    "label": "esxhost",
    "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
   },
   { "name": "emulator_server", "query": "10.160.16.4,10.160.11.5" }
  ]
 },
 "panels": [
  {
   "title": "Esxi Hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host CPU",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(vmware_host_cpu_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "vm CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 4, "y": 1 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(vmware_vm_cpu_usagemhz{host_name=~\"$esxhost\"}[1m])",
       "legendFormat": "{{ vm_name }}"
      }
     ]
    },
    {
     "title": "Host Mem Avaliable",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(vmware_host_memory_max{host_name=~\"$esxhost\"}) - (vmware_host_memory_usage{host_name=~\"$esxhost\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "vm Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 4, "y": 9 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "rate(vmware_vm_mem_usage{host_name=~\"$esxhost\"}[1m]) / 4",
       "legendFormat": "{{ vm_name }}"
      }
     ]
    },
    {
     "title": "DataStore Used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "((vmware_datastore_capacity_size{host_name=~\"$esxhost\", ds_name=~\"datastore1\"}) - (vmware_datastore_freespace_size{host_name=~\"$esxhost\", ds_name=~\"datastore1\"})) * 100 / (vmware_datastore_capacity_size{host_name=~\"$esxhost\", ds_name=~\"datastore1\"})",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Jenkins",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. CPU",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.160.50.118:9100\",mode=\"idle\"}[1m])) * 100)",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Mem Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(1- node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"10.160.50.118:9100\"} / node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.160.50.118:9100\"}) * 100",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Network Bandwidth",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"10.160.50.118:9100\", device=\"eth0\"}[1m]) * 8",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "CPU vs Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.160.50.118:9100\",mode=\"idle\"}[30s])) * 100)",
       "legendFormat": "%"
      }
     ]
    },
    {
     "title": "Mem VS Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 9, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.160.50.118:9100\"} -node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"10.160.50.118:9100\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.160.50.118:9100\"}",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Emulator-Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Emulator",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "namedprocess_namegroup_num_procs{groupname=\"emulator\",instance=~\"$emulator_server:9256\",job=\"process-exporter\"}"
      }
     ]
    },
    {
     "title": "Avg. CPU",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\", instance=~\"$emulator_server:9100\",mode=\"idle\"}[5m])) * 100)",
       "legendFormat": " {{instance}}"
      }
     ]
    },
    {
     "title": "Avg. Mem Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(1- node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=~\"$emulator_server:9100\"} / node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$emulator_server:9100\"}) * 100",
       "legendFormat": " {{instance}}"
      }
     ]
    },
    {
     "title": "Network Bandwidth",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=~\"$emulator_server:9100\", device=\"enp0s31f6\"}[1m]) * 8",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=~\"$emulator_server:9100\", device=\"enp4s0\"}[1m]) * 8",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU vs Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\", instance=~\"$emulator_server:9100\",mode=\"idle\"}[30s])) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mem VS Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$emulator_server:9100\"} -node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=~\"$emulator_server:9100\"}",
       "legendFormat": "Used -  {{instance}}"
      },
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$emulator_server:9100\"}",
       "legendFormat": "Total -  {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FTC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "FTC https call Return Code",
     "type": "stat",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "probe_http_status_code{instance=\"https://10.160.44.172/version\",job=\"ftc_check_40.31\"}",
       "legendFormat": "10.160.44.172"
      }
     ]
    },
    {
     "title": "FTC Response Time(Version Check Response)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=\"https://10.160.44.172/version\",job=\"ftc_check_40.31\"}",
       "legendFormat": "10.160.44.172"
      }
     ]
    },
    {
     "title": "DNS resolving Time in Seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(probe_dns_duration_seconds) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DNS connect time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_dns_duration_seconds{job=\"dns_check\",phase=\"connect\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DNS request time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_dns_duration_seconds{job=\"dns_check\",phase=\"request\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DNS resolve time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_dns_duration_seconds{job=\"dns_check\",phase=\"resolve\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Smoke Ping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Ping Check(RTT)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Infra-Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.160.50.8:9100\",mode=\"idle\"}[5m])) * 100)",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(1- node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"10.160.50.8:9100\"} / node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.160.50.8:9100\"}) * 100",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Network Bandwidth",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"10.160.50.8:9100\", device=\"ens160\"}[1m]) * 8",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Data Store Free",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{device=\"/dev/mapper/centos-root\",fstype=\"xfs\",instance=\"10.160.50.8:9100\",job=\"node-exporter\",mountpoint=\"/\"}"
      }
     ]
    }
   ]
  }
 ]
}