apiVersion: v1
kind: Namespace
metadata:
  name: scale-test-runner-ftc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-runner
  namespace: scale-test-runner-ftc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-runner
  template:
    metadata:
      labels:
        app: test-runner
    spec:
      containers:
      - args:
        - -c
        - wget http://10.160.50.118:8889/ftc_launch.sh -O /pytest-automation/ftc_launch.sh;/bin/bash
          ftc_launch.sh
        command:
        - /bin/bash
        env:
        - name: QT_X11_NO_MITSHM
          value: '1'
        - name: DISPLAY
          value: :88
        - name: SESSION_ID
          value: debug
        image: 10.160.16.60/pytest-automation/pytest_automation:api_perf
        imagePullPolicy: Always
        name: test-runner
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - mountPath: /tmp/.X11-unix/
          name: x11-data
        - mountPath: /dev/shm
          name: shm
      dnsConfig:
        nameservers:
        - 10.160.41.22
      hostAliases:
      - hostnames:
        - ftc.fortinet.com
        ip: 10.160.44.172
      nodeSelector:
        runner: scale
      volumes:
      - hostPath:
          path: /tmp/.X11-unix/
        name: x11-data
      - hostPath:
          path: /dev/shm
        name: shm
