RESOURCE_MAPPING = {
    "platform_operator": "assistants.api",
    "resource_manager": "resources.api",
    "image_classifier": "model.api",
    "scale_controller": "scale.api",
    "monitor": "monitor.api",
    "qr_display": "qrdisplay.api",
    "benchmark": "benchmark.api",
    "fos": "fos.api",
    "bp_proxy": "bpproxy.api",
    "bp_manager": "bpmanager.api",
    "k8s": "k8s.api",
    "upgrade": "upgrade.api",
    "datasync": "datasync.api",
    "pool": "pool.api",
    "jenkins_cloud": "jenkins_cloud.api",
    "mongodb": "mongodb.api",
    "reviewfinder": "reviewfinder.api",
    "dhub": "dhub.api",
    "browser_cloud": "browser_cloud.api"
}
