from setuptools import setup

setup(
    author='Automation Team, Zheng Nie',
    description='Test As A Service',
    install_requires=[
        'Appium-Python-Client==1.0.2',
        'in_place==0.4.0',
        'PyMySql==0.10.0',
        'opencv_python==4.10.0.84',
        'paramiko==2.7.1',
        'paramiko-expect==0.3.2',
        'pytest==6.0.1',
        'pytest-dependency==0.5.1',
        'pytest-xdist==1.34.0',
        'requests==2.23.0',
        'singleton_decorator==1.0.0',
        'selenium==3.141.0',
        'pyscreenshot==2.2',
        'flask>=2.2.2',
        'flask_restful==0.3.9',
        'PyYAML==5.3.1',
        'jsonschema==3.2.0',
        'pyotp==2.4.0',
        'GitPython==3.1.3',
        'imagehash',
        'zeep==4.0.0',
        'redis',
        'cassandra-driver',
        'pandas',
        'eventlet',
        'pika',
        'rq',
        'celery',
        'cryptography',
        'urllib3',
        'beautifulsoup4',
        'google_play_scraper==1.2.7',
        'app_store_scraper==0.3.5',
        'google-api-python-client==2.159.0',
        'pydantic'
    ],
    packages=[],
    name='taas',
    version='1.4',
    zip_safe=False
)
